/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador_FRM_MenuPrincipal;
import Modelo.MetodosUsuarioArchivos;

/**
 *
 * @author chelvivil
 */
public class FRM_MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FRM_MenuPrincipal
     */
    Controlador_FRM_MenuPrincipal controlador_FRM_MenuPrincipal;
    FRM_SeleccionarTipo valor;
       FRM_LoginUsuario log;  
        MetodosUsuarioArchivos log2;
        FRM_LoginArchivos vent;
   int valorA=0;
    public FRM_MenuPrincipal(FRM_SeleccionarTipo valor)throws Exception {
        initComponents();
        this.setLocation(100, 100);
        setSize(756,280);

        controlador_FRM_MenuPrincipal= new Controlador_FRM_MenuPrincipal(this);
        this.valor = valor;
        if(seleccionar()==3){
            log = new FRM_LoginUsuario(this);
        if(log.visible()){
        log.setVisible(true);    
        }else{
        this.setVisible(true);
        } 
        }
        if(seleccionar()==1)
        {log2=new MetodosUsuarioArchivos();
        vent = new FRM_LoginArchivos(this);
        if(log2.verificarExistenciaDeArchivoDeUsuarios()){
            vent.setVisible(true);
        }else{
            this.setVisible(true);
        }
       
            
        }
         if(seleccionar()==2){
            this.setVisible(true);
        }
           
        
       
       seleccionar();
      
       utilizar();
       
       agregarEventos();
       
        
    }
    public void agregarEventos(){
         this.jm_Salir.addActionListener(controlador_FRM_MenuPrincipal);
        this.jmi_Estudiante.addActionListener(controlador_FRM_MenuPrincipal);
        this.jmi_Cursos.addActionListener(controlador_FRM_MenuPrincipal);
        this.jmi_Matricula.addActionListener(controlador_FRM_MenuPrincipal);
        this.jm_RegistrarUsuario.addActionListener(controlador_FRM_MenuPrincipal);
        
    }
   
     public int seleccionar(){
        valorA=Integer.parseInt(valor.asignarValor());
        return valorA;
        
     }
     
     
   public void utilizar(){
    switch(seleccionar()){
        case 1:
      System.out.println("Aqui se llaman los Planos");
            break;     
        
        case 2:
            System.out.println("Aqui se llaman los XML");
           break;
            
        case 3:
          System.out.println("Aqui se llama la BD");      
           break;     
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        fondo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jm_Salir = new javax.swing.JMenuItem();
        jm_registro = new javax.swing.JMenu();
        jmi_Estudiante = new javax.swing.JMenuItem();
        jmi_Cursos = new javax.swing.JMenuItem();
        jmi_Matricula = new javax.swing.JMenuItem();
        jm_Usuario = new javax.swing.JMenu();
        jm_RegistrarUsuario = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setPreferredSize(new java.awt.Dimension(744, 299));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondoMP2.png"))); // NOI18N

        jMenu1.setText("Salir");

        jm_Salir.setText("Salir");
        jMenu1.add(jm_Salir);

        jMenuBar1.add(jMenu1);

        jm_registro.setText("Registro");

        jmi_Estudiante.setText("Estudiante");
        jm_registro.add(jmi_Estudiante);

        jmi_Cursos.setText("Cursos");
        jm_registro.add(jmi_Cursos);

        jmi_Matricula.setText("Matricula");
        jm_registro.add(jmi_Matricula);

        jMenuBar1.add(jm_registro);

        jm_Usuario.setText("Usuario");

        jm_RegistrarUsuario.setText("Registrar Usuario");
        jm_Usuario.add(jm_RegistrarUsuario);

        jMenuBar1.add(jm_Usuario);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 744, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jm_RegistrarUsuario;
    private javax.swing.JMenuItem jm_Salir;
    private javax.swing.JMenu jm_Usuario;
    private javax.swing.JMenu jm_registro;
    private javax.swing.JMenuItem jmi_Cursos;
    private javax.swing.JMenuItem jmi_Estudiante;
    private javax.swing.JMenuItem jmi_Matricula;
    // End of variables declaration//GEN-END:variables
}
