/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador_FRM_SeleccionarTipo;
import java.awt.event.ActionListener;

/**
 *
 * @author chelvivil
 */
public class FRM_SeleccionarTipo extends javax.swing.JFrame {

    /**
     * Creates new form FRM_SeleccionarTipo
     */
    Controlador_FRM_SeleccionarTipo controlador; 
    private String valor="";
    public FRM_SeleccionarTipo() {
        initComponents();
        setSize(756,280);
        controlador=new Controlador_FRM_SeleccionarTipo(this);
        agregarEventos(controlador);
    }
    public void agregarEventos(ActionListener controlador){
        this.btn_Entrar.addActionListener(controlador);
    }
    public String asignarValor(){
        if(this.rbt_Archivos.isSelected()){
           valor=""+1; 
           
        }
        else{
               if(this.rbt_XML.isSelected()) {
                   valor=""+2;
                  
                   
               }
               else{
                     if(this.rbt_BD.isSelected()) {
                         valor=""+3;
                        
                     }     
                           }
                   }
        
        return valor;
        
    }
    public void imp(){
         System.out.println(valor);
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        rbt_Archivos = new javax.swing.JRadioButton();
        rbt_XML = new javax.swing.JRadioButton();
        rbt_BD = new javax.swing.JRadioButton();
        btn_Entrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(756, 298));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup1.add(rbt_Archivos);
        rbt_Archivos.setText("Archivos");
        rbt_Archivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbt_ArchivosActionPerformed(evt);
            }
        });
        getContentPane().add(rbt_Archivos, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, -1, -1));

        buttonGroup1.add(rbt_XML);
        rbt_XML.setText("XML");
        rbt_XML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbt_XMLActionPerformed(evt);
            }
        });
        getContentPane().add(rbt_XML, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, -1, -1));

        buttonGroup1.add(rbt_BD);
        rbt_BD.setText("Bases de Datos");
        rbt_BD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbt_BDActionPerformed(evt);
            }
        });
        getContentPane().add(rbt_BD, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, -1, -1));

        btn_Entrar.setText("ENTRAR");
        getContentPane().add(btn_Entrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, 210, 250));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondoSeleccion.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 770, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbt_ArchivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbt_ArchivosActionPerformed
asignarValor();        
 imp();
    }//GEN-LAST:event_rbt_ArchivosActionPerformed

    private void rbt_XMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbt_XMLActionPerformed
        asignarValor();        
 imp();
    }//GEN-LAST:event_rbt_XMLActionPerformed

    private void rbt_BDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbt_BDActionPerformed
asignarValor();        
 imp();
    }//GEN-LAST:event_rbt_BDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRM_SeleccionarTipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRM_SeleccionarTipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRM_SeleccionarTipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRM_SeleccionarTipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRM_SeleccionarTipo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Entrar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton rbt_Archivos;
    private javax.swing.JRadioButton rbt_BD;
    private javax.swing.JRadioButton rbt_XML;
    // End of variables declaration//GEN-END:variables

    
}
