/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador_FRM_RegistroUsuarios;
import javax.swing.JOptionPane;

/**
 *
 * @author chelvivil
 */
public class FRM_RegistroUsuario extends javax.swing.JFrame {

    /**
     * Creates new form FRM_RegistroUsuario
     */
    Controlador_FRM_RegistroUsuarios controlador;
    public FRM_RegistroUsuario(FRM_MenuPrincipal control) {
        initComponents();
        controlador = new Controlador_FRM_RegistroUsuarios(this,control);
        gUI_Botones1.agregarEventos(controlador);
       
    }
    public String[] devolverInformacion(){
         String arreglo[];
        arreglo=new String[4];
        arreglo[0]=jt_Cedula.getText();
        arreglo[1]=jt_Nombre.getText();
        arreglo[2]=jt_Usuario.getText();
        arreglo[3]=jt_Conttraseña.getText();
        return arreglo;
    }
    
    public String[] devolverInformacion2(){
         String arreglo[];
        arreglo=new String[4];
        arreglo[0]=jt_Usuario.getText();
        arreglo[1]=jt_Nombre.getText();
        arreglo[2]=jt_Conttraseña.getText();
        arreglo[3]=jt_Cedula.getText();
        return arreglo;
    }
   public void mostrarInformacion(String arreglo[])
    {
        this.jt_Cedula.setText(arreglo[0]);
        this.jt_Nombre.setText(arreglo[1]);
        this.jt_Usuario.setText(arreglo[2]);
                this.jt_Conttraseña.setText(arreglo[3]);

    }
   public void mostrarInformacion2(String arreglo[]){
        this.jt_Nombre.setText(arreglo[0]);
        this.jt_Conttraseña.setText(arreglo[1]);
        this.jt_Cedula.setText(arreglo[2]);
    }
   public String devolverUsuario(){
        return this.jt_Usuario.getText();
    }
   public void mostrarMensaje(String mensaje)
    {
        JOptionPane.showMessageDialog(null,mensaje);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jt_Cedula = new javax.swing.JTextField();
        jt_Nombre = new javax.swing.JTextField();
        jt_Usuario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jt_Conttraseña = new javax.swing.JTextField();
        gUI_Botones1 = new Vista.GUI_Botones();
        jLabel5 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(420, 269));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Cedula");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 17, -1, -1));

        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 62, -1, -1));

        jLabel3.setText("Usuario");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 107, -1, -1));
        getContentPane().add(jt_Cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 12, 301, -1));
        getContentPane().add(jt_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 57, 301, -1));
        getContentPane().add(jt_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 102, 301, -1));

        jLabel4.setText("Contraseña");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 159, -1, -1));
        getContentPane().add(jt_Conttraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 154, 301, -1));

        gUI_Botones1.setOpaque(false);
        getContentPane().add(gUI_Botones1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pag.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -3, 420, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Vista.GUI_Botones gUI_Botones1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jt_Cedula;
    private javax.swing.JTextField jt_Conttraseña;
    private javax.swing.JTextField jt_Nombre;
    private javax.swing.JTextField jt_Usuario;
    // End of variables declaration//GEN-END:variables
}
