/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador_FRM_MantenimientoCursos;
import javax.swing.JOptionPane;

/**
 *
 * @author tecnologiamultimedia
 */
public class FRM_MantenimientoCursos extends javax.swing.JFrame {

    /**
     * Creates new form FRM_MantenimientoCursos
     */
    public Controlador_FRM_MantenimientoCursos controlador;
    
    public FRM_MantenimientoCursos(FRM_MenuPrincipal control) {
        initComponents();
        setSize(400,300);
        controlador = new Controlador_FRM_MantenimientoCursos(this,control);
        this.gUI_Botones1.agregarEventos(controlador);
       
    }
     public void mostrarMensaje(String mensaje)
    {
        JOptionPane.showMessageDialog(null,mensaje);
    }
    public String[] devolverInformacion()
    {
        return this.gUI_InformacionCursos1.devolverInformacion();
    }
    public String devolverSigla()
    {
        return this.gUI_InformacionCursos1.devolverSigla();
    }
    public void mostrarInformacion(String arreglo[])
    {
        this.gUI_InformacionCursos1.mostrarInformacion(arreglo);
    }
    public void mostrarInformacionXML(String arreglo[])
    {
        this.gUI_InformacionCursos1.mostrarInformacionXML(arreglo);
    }
    public void habilitarAgregar(){
    this.gUI_Botones1.habilitarAgregar();
    this.gUI_InformacionCursos1.habilitarOpciones();
    
    }
    public void habilitarOpciones(){
    this.gUI_Botones1.habilitarOpciones();
    this.gUI_InformacionCursos1.habilitarOpciones();
    
    }
    
    public void desahabilitarSigla(){
    this.gUI_InformacionCursos1.desahabilitarSigla();
    }
    public void limpiarInterfaz(){
    
    this.gUI_InformacionCursos1.limpiarInterfaz();
    }
     
      public void estadoInicial(){
    this.gUI_InformacionCursos1.estadoInicial();
    this.gUI_Botones1.estadoInicial();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gUI_InformacionCursos1 = new Vista.GUI_InformacionCursos();
        gUI_Botones1 = new Vista.GUI_Botones();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(285, 275));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gUI_InformacionCursos1.setOpaque(false);
        getContentPane().add(gUI_InformacionCursos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, -1, -1));

        gUI_Botones1.setOpaque(false);
        getContentPane().add(gUI_Botones1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pag.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setPreferredSize(new java.awt.Dimension(809, 300));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -3, 400, 280));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Vista.GUI_Botones gUI_Botones1;
    private Vista.GUI_InformacionCursos gUI_InformacionCursos1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
