package Vista;

import Controlador.Controlador_FRM_LoginArchivos;
//import Controlador.Controlador_Usuario;
import javax.swing.JOptionPane;


public class FRM_LoginArchivos extends javax.swing.JFrame {

    Controlador_FRM_LoginArchivos controladorLogin;
    FRM_MenuPrincipal principal;
    FRM_RegistroUsuario usuarios;
    
    
    
    public FRM_LoginArchivos(FRM_MenuPrincipal principal) throws Exception {
        this.principal=principal;
//        this.principal=new FRM_MenuPrincipal();
        usuarios= new FRM_RegistroUsuario(principal);
        
        
        initComponents();
        
        this.setLocation(200,50);
        controladorLogin=new Controlador_FRM_LoginArchivos(this,principal);
        this.jb_Login.addActionListener(controladorLogin);
    }
    
    public void hacerLogin()
    {
        JOptionPane.showMessageDialog(null,"Existen usuarios registrados, inicie con uno de esos");
        
        this.setVisible(true);
//        principal.setVisible(true);
        
    }
    
    public void noHacerLogin()
    {
        JOptionPane.showMessageDialog(null,"no existen usuarios registrado,registre uno");
       setVisible(false);
      usuarios.setVisible(true);
       
        
        
    }
    
    public void mostrarVentana()
    {
        setVisible(false);
        principal.setVisible(true);
    }
    
    public void limpiar()
    {
        jt_ContraseñaLo.setText("");
        jt_NombreUsuarioLo.setText("");
    }
    
    public String getJtNombreUsuario()
    {
        return this.jt_NombreUsuarioLo.getText();
    }
    
    public String getJtContraseña()
    {
        return this.jt_ContraseñaLo.getText();
    }
    
    public String devolverNombreUsuario()
    {
        return jt_NombreUsuarioLo.getText();
    }
    
    public String devolverContraseña()
    {
       return jt_ContraseñaLo.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jt_NombreUsuarioLo = new javax.swing.JTextField();
        jt_ContraseñaLo = new javax.swing.JTextField();
        jb_Login = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setText("Nombre Usuario:");

        jLabel2.setText("Contraseña:");

        jt_NombreUsuarioLo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jt_NombreUsuarioLoKeyPressed(evt);
            }
        });

        jt_ContraseñaLo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_ContraseñaLoActionPerformed(evt);
            }
        });
        jt_ContraseñaLo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jt_ContraseñaLoKeyPressed(evt);
            }
        });

        jb_Login.setText("Entrar");
        jb_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_LoginActionPerformed(evt);
            }
        });
        jb_Login.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jb_LoginKeyPressed(evt);
            }
        });

        jLabel3.setText("INICIAR SESION");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jt_NombreUsuarioLo)
                    .addComponent(jt_ContraseñaLo, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE))
                .addGap(18, 30, Short.MAX_VALUE)
                .addComponent(jb_Login)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(160, 160, 160))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jt_NombreUsuarioLo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jb_Login)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jt_ContraseñaLo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jt_ContraseñaLoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_ContraseñaLoActionPerformed

        
    }//GEN-LAST:event_jt_ContraseñaLoActionPerformed

    private void jt_NombreUsuarioLoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jt_NombreUsuarioLoKeyPressed

         System.out.println("codigo de la tecla_"+evt.getKeyCode());
        
        if(evt.getKeyCode()==10)
        {
        controladorLogin.buscar();    
            
        }

    }//GEN-LAST:event_jt_NombreUsuarioLoKeyPressed

    private void jb_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_LoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_LoginActionPerformed

    private void jb_LoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jb_LoginKeyPressed
       
        System.out.println("codigo de la tecla_"+evt.getKeyCode());
        
        if(evt.getKeyCode()==10)
        {
        controladorLogin.buscar();    
            
        }
    }//GEN-LAST:event_jb_LoginKeyPressed

    private void jt_ContraseñaLoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jt_ContraseñaLoKeyPressed
       System.out.println("codigo de la tecla_"+evt.getKeyCode());
        
        if(evt.getKeyCode()==10)
        {
        controladorLogin.buscar();    
            
        }
    }//GEN-LAST:event_jt_ContraseñaLoKeyPressed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jb_Login;
    private javax.swing.JTextField jt_ContraseñaLo;
    private javax.swing.JTextField jt_NombreUsuarioLo;
    // End of variables declaration//GEN-END:variables
}
